# Dockerfile-React
FROM node:latest as build

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json
COPY ["package.json", "package-lock.json*", "./"]

# 安装依赖
RUN npm install

# 复制源代码
COPY . .

# 构建应用
RUN npm run build

# 配置 Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
