# Dockerfile-React
FROM node:16 as build

ARG PAT

# 安装 git

RUN apt-get update && apt-get install -y git

# 克隆您的 React 仓库
RUN git clone https://$PAT@github.com/xpnice/SmartConFE.git /app

# 设置工作目录
WORKDIR /app

# 安装依赖
RUN npm install

# 构建应用
RUN npm run build

# 配置 Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx-react.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
