version: '3'
services:
  react:
    build:
      context: ./path-to-react
      dockerfile: Dockerfile-React
    ports:
      - "3000:80"
    networks:
      - webnet

  flask:
    build:
      context: ./path-to-flask
      dockerfile: Dockerfile-Flask
    ports:
      - "8000:8000"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react
      - flask
    networks:
      - webnet

networks:
  webnet:
