# Dockerfile-Flask
FROM python:3.8-slim

# 安装 git
RUN apt-get update && apt-get install -y git

# 克隆 Flask 仓库
RUN git clone https://github.com/girotte-tao/safe_lift_environment.git /app

# 设置工作目录
WORKDIR /app

# 安装依赖，包括 Gunicorn
COPY requirements.txt /app/
RUN pip install -r requirements.txt
RUN pip install gunicorn

# 复制源代码
COPY . /app

# 暴露端口
EXPOSE 8000

# 设置启动命令，使用 Gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:8000", "app:app"]
