version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.react
      args:
        - PAT=${PAT}
    # ports:
    #   - "3000:80"
    networks:
      - webnet

  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
      args:
        - PAT=${PAT}
    # ports:
    #   - "8000:8000"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "1935:1935"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react
      - flask
    networks:
      - webnet

networks:
  webnet:
